### PR TITLE
Add minisymposium agenda

### PR DESCRIPTION
**Pull request by rkurchin**
Signed-off-by: Rachel Kurchin <rkurchin@cmu.edu>

### CODE REVIEW

**Comment by jgreener64** [comment]
Looks good.

**Comment by mfherbst** [comment]
Maybe put the Juliacon 2022 stuff on a separate page to not push the projects listing down too much?

Otherwise looks good to me.

**Review by mfherbst — COMMENTED** [review]
Maybe put the Juliacon 2022 stuff on a separate page to not push the projects listing down too much?

Otherwise looks good to me.

**Comment by rkurchin** [comment]
Okay so it turns out out menu link on the side never actually worked...the link to go back to the homepage now works, but I tried for probably 30-45 minutes and can't figure out how to get the menu bar link to the JuliaCon page to work. Maybe I've missed something dumb here...I also really don't know CSS or HTML beyond absolute basics, so that's not helping. At any rate, the link in the body of the homepage to the JuliaCon page is functional, so maybe we could just use a different template and/or ditch the menu?

**Comment by mfherbst** [comment]
No problem @rkurchin. I think you just misinterpreted the Franklin docs as to where the page files end up living in the generated website.

**Pull request merged**
